language: groovy

services:
  - mongodb

jdk:
  - oraclejdk8

script:
  - ./gradlew build integTest

before_install:
  - chmod +x gradlew

after_success:
- "./gradlew jacocoTestReport coveralls --debug"